FROM composer:2.6.4 AS composer

FROM alpine:3.18.4
EXPOSE 9000/tcp

RUN apk add git \
	curl \
	nodejs \
	npm \
	php82 \
	php82-curl \
	php82-iconv \
	php82-openssl \
	php82-zip \
	php82-mbstring \
	php82-common \
	php82-phar \
	php82-simplexml \
	php82-dom \
	php82-tokenizer \
	php82-xml \
	php82-xmlwriter \
	php82-fpm

COPY --from=composer /usr/bin/composer /usr/bin/composer

# Create symlink for php
RUN ln -s /usr/bin/php82 /usr/bin/php
