services:
  workspace:
    build:
      context: ./workspace
    tty: true
    expose:
      - "9000"
    environment:
      - IA_LOG_FOLDER=/intruder-alert/backend/data/logs
    volumes:
      - ../:/intruder-alert
      - vendor:/intruder-alert/backend/vendor
      - geoip2:/intruder-alert/backend/data/geoip2
      - ./fail2ban-logs:/intruder-alert/backend/data/logs:ro
    working_dir: /intruder-alert

  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:8080
    volumes:
      - ../:/intruder-alert:ro
      - vendor:/intruder-alert/backend/vendor:ro
    working_dir: /intruder-alert

volumes:
  vendor:
  geoip2:
