services:
  workspace:
    build:
      context: ./workspace
    tty: true
    expose:
      - "9000"
    environment:
      - IA_LOG_FOLDER=/intruder-alert/backend/data/logs
      - XDEBUG_MODE=coverage
    volumes:
      - ../:/intruder-alert
      - vendor:/intruder-alert/backend/vendor
      - node_modules:/intruder-alert/node_modules
      - geoip2:/intruder-alert/backend/data/geoip2
      - ./fail2ban-logs:/intruder-alert/backend/data/logs:ro
      - ./workspace/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /intruder-alert

  nginx:
    image: nginx:1.27-alpine3.20-slim
    ports:
      - 8080:8080
    volumes:
      - ../:/intruder-alert:ro
      - vendor:/intruder-alert/backend/vendor:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    working_dir: /intruder-alert

volumes:
  vendor:
  node_modules:
  geoip2:
