services:
  workspace:
    build:
      context: ./workspace
    tty: true
    environment:
      - IA_LOG_FOLDER=/intruder-alert/backend/data/logs
    volumes:
      - ../:/intruder-alert
      - ./fail2ban-logs:/intruder-alert/backend/data/logs:ro
    working_dir: /intruder-alert

  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:8080
    volumes:
      - ../:/intruder-alert:ro
    working_dir: /intruder-alert

  php:
    build:
      context: ./php
    expose:
      - "9000"
    environment:
      - IA_LOG_FOLDER=/intruder-alert/backend/data/logs
    volumes:
      - ../:/intruder-alert
      - ./fail2ban-logs:/intruder-alert/backend/data/logs:ro
    working_dir: /intruder-alert
