name: Code quality (js)

on:
  pull_request:
    paths:
      - "**.js"
  push:
    branches: main
    paths:
      - "**.js"

permissions:
  contents: read

jobs:
  eslint:
    name: Oxlint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.14
          cache: 'npm'

      - name: Installing dependencies
        run: npm ci --ignore-scripts

      - name: Run Oxlint
        run: npm run lint
