name: Code quality

on:
  pull_request:
    paths:
      - "**.js"
      - ".github/workflows/js-code-quality.yml"
  push:
    branches: main
    paths:
      - "**.js"
      - ".github/workflows/js-code-quality.yml"

permissions:
  contents: read

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Setup node
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
      with:
        node-version: 20.3
        cache: 'npm'

    - name: Installing dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
